version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: artichub_db
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_USER: youruser
      MYSQL_PASSWORD: yourpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  django:
    build: .
    container_name: django_app
    restart: always
    depends_on:
      - mysql
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_NAME=artichub_db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=yourpassword
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  mysql_data:
