# Generated by Django 5.1.6 on 2025-03-23 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("yearCreation", models.IntegerField(blank=True, null=True)),
                ("signed", models.BooleanField(default=False)),
                ("condition", models.CharField(blank=True, max_length=255, null=True)),
                ("period", models.CharField(blank=True, max_length=255, null=True)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("image", models.URLField(blank=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "saleType",
                    models.CharField(
                        choices=[("Sale", "Sale"), ("Auction", "Auction")],
                        default="Sale",
                        max_length=255,
                    ),
                ),
                ("auctionStartDate", models.DateTimeField(blank=True, null=True)),
                ("auctionEndDate", models.DateTimeField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("bids", models.JSONField(blank=True, default=list, null=True)),
                ("highestBid", models.JSONField(blank=True, null=True)),
                ("reviews", models.JSONField(blank=True, default=list, null=True)),
                (
                    "seller",
                    models.ForeignKey(
                        limit_choices_to={"role": "artist"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="art_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Art Product",
                "verbose_name_plural": "Art Products",
            },
        ),
    ]
