# Generated by Django 5.1.6 on 2025-03-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Arts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artproduct",
            name="condition",
            field=models.CharField(blank=True, max_length=755, null=True),
        ),
    ]
