# Generated by Django 5.1.6 on 2025-04-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Arts", "0002_alter_artproduct_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="artproduct",
            name="t2ype",
            field=models.CharField(
                choices=[
                    ("painting", "Painting"),
                    ("sculpture", "Sculpture"),
                    ("photography", "Photography"),
                    ("digital", "Digital"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
