# Generated by Django 5.1.6 on 2025-04-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Arts", "0003_artproduct_t2ype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artproduct",
            name="yearCreation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
